name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUSH_BRANCH_NAME: "main"
          SHOW_TIMEZONE: "False"
          SHOW_PROJECTS : "True"
          SHOW_EDITORS : "True"
          SHOW_OS : "True"
          SHOW_LANGUAGE : "True"
          SYMBOL_VERSION : "1"
          SHOW_LINES_OF_CODE : "False"
          SHOW_LOC_CHART : "False"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_TOTAL_CODE_TIME : "False"
          SHOW_SHORT_INFO : "False"
          SHOW_COMMIT : "True"
          SHOW_DAYS_OF_WEEK : "True"
          SHOW_LANGUAGE_PER_REPO : "True"
          SHOW_UPDATED_DATE : "True"
          UPDATED_DATE_FORMAT : "%d/%m/%Y %H:%M:%S"
          # COMMIT_BY_ME : "True" # CAUSES ERROR
          COMMIT_MESSAGE : "Updated README with Dev Metrics"
